name: Accessibility

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  a11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - run: yarn install --frozen-lockfile

      - name: Compile styles
        run: yarn css:build

      - name: Run accessibility tests
        run: yarn storybook:axe
