name: "Chromatic"

on: push
jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - run: yarn install --frozen-lockfile

      - run: yarn css:build

      - name: Publish to Chromatic
        uses: chromaui/action@v10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: c6b96f9648b6
