name: Lint and format

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  css_stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: yarn install --frozen-lockfile

      - name: Run stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          stylelint_input: "src/**/*.scss"
          reporter: github-pr-review
          fail_on_error: true
          level: error

  js_eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: yarn install --frozen-lockfile

      - name: Run eslint
        run: yarn js:eslint

  css_prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - run: yarn install --frozen-lockfile

      - name: Run Prettier
        run: yarn css:prettier -- --check

  js_prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - run: yarn install --frozen-lockfile

      - name: Run Prettier
        run: yarn js:prettier -- --check

  markdownlint:
    name: Lint markdown
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install
      - name: Install problem matcher
        uses: xt0rted/markdownlint-problem-matcher@v1
      - name: Lint markdown
        run: yarn lint:markdown
