name: Lint and format

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  css-lint:
    name: CSS Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      - run: yarn install --frozen-lockfile

      - name: Run css:lint
        run: yarn css:lint

  js-lint:
    name: JS Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      - run: yarn install --frozen-lockfile

      - name: Run js:lint
        run: yarn js:lint

  markdown-linkt:
    name: Markdown Linter
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      - run: yarn install --frozen-lockfile

      - name: Run markdown:lint
        run: yarn markdown:lint
