name: Lint and format

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  css_stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm ci

      - name: Run stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          stylelint_input: "src/styles/scss/**/*.scss"
          reporter: github-pr-review
          fail_on_error: false
          level: error

  js_eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm ci

      - name: Run eslint
        run: npm run js:eslint

  css_prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - run: npm ci

      - name: Run Prettier
        run: npm run css:prettier -- --check

  js_prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - run: npm ci

      - name: Run Prettier
        run: npm run js:prettier -- --check
